<a href="https://colab.research.google.com/github/OleksandrKarpenkoUA/pytorch-tutorial-for-me/blob/main/Pytorch_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
import torchvision as tv

import numpy as np
import matplotlib.pyplot as plt
import cv2
import os

In [ ]:
trans = tv.transforms.Compose[{
    tv.transforms.ToTensor()
}]

TypeError: 'type' object is not subscriptable

In [ ]:
ds_mnist = tv.datasets.MNISt('./datasets', download=True. transform=trans)

SyntaxError: invalid syntax (<ipython-input-21-7f9a305520f1>, line 1)

In [ ]:
data = [1, 2, 3]
tensor = torch.tensor(data)
tensor

tensor([1, 2, 3])

In [ ]:
tensor = torch.ones(2, 3)
tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
import numpy as np
np_array = np.array([[1, 2, 3], [4, 5, 6]])
np_array

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
tensor = torch.from_numpy(np_array)
tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
tensor = torch.tensor([1, 2, 3])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
rand_tensor = torch.rand(2, 3, 4)
rand_tensor

tensor([[[0.2516, 0.2968, 0.7311, 0.4089],
         [0.3651, 0.1824, 0.2367, 0.1694],
         [0.4037, 0.3818, 0.7270, 0.2000]],

        [[0.3837, 0.1794, 0.7589, 0.6982],
         [0.7704, 0.5923, 0.3050, 0.3323],
         [0.9892, 0.1685, 0.0669, 0.1351]]])

In [ ]:
rand_tensor = torch.rand(2, 3,)
rand_tensor

tensor([[0.2554, 0.6072, 0.7064],
        [0.0518, 0.5706, 0.8576]])

In [ ]:
rand_tensor.device

device(type='cpu')

In [ ]:
rand_tensor.shape

torch.Size([2, 3])

In [ ]:
rand_tensor.dtype

torch.float32

In [ ]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor = tensor.reshape(6)
tensor

tensor([1, 2, 3, 4, 5, 6])

In [ ]:
tensor[:3]

tensor([1, 2, 3])

In [ ]:
tensor[2:5]

tensor([3, 4, 5])

In [ ]:
tensor[1, -1]

IndexError: too many indices for tensor of dimension 1

In [ ]:
tensor = torch.tensor([[1, 2, 3, 102, 12, 111], [4, 5, 6, 7, 8, 9]])
tensor.view(2, -1)

tensor([[  1,   2,   3, 102,  12, 111],
        [  4,   5,   6,   7,   8,   9]])

In [ ]:
tensor.reshape(-1, 3)

tensor([[  1,   2,   3],
        [102,  12, 111],
        [  4,   5,   6],
        [  7,   8,   9]])

In [ ]:
data_a = np.arange(0, 5)
data_b = np.arange(5, 10)

In [ ]:
data_a

array([0, 1, 2, 3, 4])

In [ ]:
data_b

array([5, 6, 7, 8, 9])

In [ ]:
tensor_a = torch.tensor([1, 2, 3])
tensor_b = torch.tensor([4, 5, 6])


In [ ]:
# add
torch.add(tensor_a, tensor_b)

tensor([5, 7, 9])

In [ ]:
tensor_a

tensor([1, 2, 3])

In [ ]:
add = tensor_a.add_(tensor_b) # tensor_a = tensor_a + tensor_b

In [ ]:
add

tensor([5, 7, 9])

In [ ]:
# sub
torch.sub(tensor_b, tensor_a)

tensor([-1, -2, -3])

In [ ]:
# mul
torch.mul(tensor_a, tensor_b)

tensor([20, 35, 54])

In [ ]:
# div
torch.div(tensor_b, tensor_a)

tensor([0.8000, 0.7143, 0.6667])

In [ ]:
tensor_a % tensor_b

tensor([1, 2, 3])

In [ ]:
torch.pow(tensor_a, tensor_b)

tensor([   625,  16807, 531441])

In [ ]:
# remainder
torch.remainder(tensor_b, tensor_a)

tensor([4, 5, 6])

In [ ]:
import torch.nn.functional as F
import torch.nn as nn
import torch

In [ ]:
class Model(nn.Module):
  def __init__(self, in_features=4, h1=8, h2=9, out_features=3):
    super().__init__()
    self.fc1 = nn.Linear(in_features, h1)
    self.fc2 = nn.Linear(h1, h2)
    self.out = nn.Linear(h2, out_features)

    def forward(self, x):
      x = F.relu(self.fc1(x))
      x = F.relu(self.fc2(x))
      x = self.out(x)

      return x

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd

In [ ]:
url = 'https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv'
my_df = pd.read_csv(url)
my_df

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [ ]:
my_df['variety'] = my_df['variety'].replace('Setosa', 0.0)
my_df['variety'] = my_df['variety'].replace('Versicolor', 1.0)
my_df['variety'] = my_df['variety'].replace('Virginica', 2.0)

In [ ]:
my_df

sepal.length  sepal.width  petal.length  petal.width  variety
0             5.1          3.5           1.4          0.2      0.0
1             4.9          3.0           1.4          0.2      0.0
2             4.7          3.2           1.3          0.2      0.0
3             4.6          3.1           1.5          0.2      0.0
4             5.0          3.6           1.4          0.2      0.0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3      2.0
146           6.3          2.5           5.0          1.9      2.0
147           6.5          3.0           5.2          2.0      2.0
148           6.2          3.4           5.4          2.3      2.0
149           5.9          3.0           5.1          1.8      2.0

[150 rows x 5 columns]

In [ ]:
X = my_df.drop('variety', axis=1)
y = my_df['variety']

In [ ]:
X = X.values
y = y.values

In [ ]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=41)

In [ ]:
import torch
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)

In [ ]:
y_train = torch.LongTensor(y_train)
y_test = torch.LongTensor(y_test)

In [ ]:
criterion = nn.CrossEntropyLoss()

In [ ]:
model = Model()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

In [ ]:
model.parameters

<bound method Module.parameters of Model(
  (fc1): Linear(in_features=4, out_features=8, bias=True)
  (fc2): Linear(in_features=8, out_features=9, bias=True)
  (out): Linear(in_features=9, out_features=3, bias=True)
)>

In [ ]:
epochs = 100
losses = []
for i in range(epochs):
  y_pred = model.forward(X_train)

NotImplementedError: Module [Model] is missing the required "forward" function

In [ ]:
import torchvision
import torchvision.transforms as transforms

In [ ]:
transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,), (0.5,))])

In [ ]:
trainset = torchvision.datasets.FashionMNIST(root='./data', train=True, download=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)

In [ ]:
testset = torchvision.datasets.FashionMNIST(root='./data', train=False, download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=64, shuffle=False)

In [ ]:
class SimpleNet(nn.Module):
  def __init__(self):
    super(SimpleNet, self).__init__()
    self.fc1 = nn.Linear(28 * 28, 128)
    self.fc2 = nn.Linear(128, 64)
    self.fc3 = nn.Linear(64, 10)

    def forward(self, x):
      x = x.view(-1, 28 * 28)
      x = torch.relu(self.fc1(x))
      x = torch.relu(self.fc2(x))
      x = self.fc3(x)

      return x

net = SimpleNet


In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms

# 1. Завантаження даних
transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,), (0.5,))])

trainset = torchvision.datasets.FashionMNIST(root='./data', train=True, download=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)

testset = torchvision.datasets.FashionMNIST(root='./data', train=False, download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=64, shuffle=False)

# 2. Визначення нейронної мережі
class SimpleNet(nn.Module):
    def __init__(self):
        super(SimpleNet, self).__init__()
        self.fc1 = nn.Linear(28 * 28, 128)
        self.fc2 = nn.Linear(128, 64)
        self.fc3 = nn.Linear(64, 10)

    def forward(self, x):
        x = x.view(-1, 28 * 28)  # Перетворення зображення у вектор
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        x = self.fc3(x)
        return x

net = SimpleNet()

# 3. Визначення функції втрат та оптимізатора
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr=0.01, momentum=0.9)

# 4. Тренування нейронної мережі
for epoch in range(5):  # Кількість епох
    running_loss = 0.0
    for i, data in enumerate(trainloader, 0):
        inputs, labels = data

        optimizer.zero_grad()  # Очищення градієнтів

        outputs = net(inputs)  # Передбачення мережі
        loss = criterion(outputs, labels)  # Обчислення втрат
        loss.backward()  # Зворотне поширення
        optimizer.step()  # Оновлення ваг

        running_loss += loss.item()
        if i % 100 == 99:    # Виведення кожні 100 батчів
            print(f'[Epoch {epoch + 1}, Batch {i + 1}] loss: {running_loss / 100:.3f}')
            running_loss = 0.0

print('Finished Training')

# 5. Тестування нейронної мережі
correct = 0
total = 0
with torch.no_grad():
    for data in testloader:
        images, labels = data
        outputs = net(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

print(f'Accuracy of the network on the 10000 test images: {100 * correct / total:.2f}%')

[Epoch 1, Batch 100] loss: 1.256
[Epoch 1, Batch 200] loss: 0.645
[Epoch 1, Batch 300] loss: 0.565
[Epoch 1, Batch 400] loss: 0.514
[Epoch 1, Batch 500] loss: 0.474
[Epoch 1, Batch 600] loss: 0.465
[Epoch 1, Batch 700] loss: 0.479
[Epoch 1, Batch 800] loss: 0.442
[Epoch 1, Batch 900] loss: 0.442
[Epoch 2, Batch 100] loss: 0.436
[Epoch 2, Batch 200] loss: 0.409
[Epoch 2, Batch 300] loss: 0.407
[Epoch 2, Batch 400] loss: 0.409
[Epoch 2, Batch 500] loss: 0.385
[Epoch 2, Batch 600] loss: 0.404
[Epoch 2, Batch 700] loss: 0.390
[Epoch 2, Batch 800] loss: 0.382
[Epoch 2, Batch 900] loss: 0.375
[Epoch 3, Batch 100] loss: 0.365
[Epoch 3, Batch 200] loss: 0.369
[Epoch 3, Batch 300] loss: 0.372
[Epoch 3, Batch 400] loss: 0.356
[Epoch 3, Batch 500] loss: 0.366
[Epoch 3, Batch 600] loss: 0.342
[Epoch 3, Batch 700] loss: 0.345
[Epoch 3, Batch 800] loss: 0.373
[Epoch 3, Batch 900] loss: 0.347
[Epoch 4, Batch 100] loss: 0.353
[Epoch 4, Batch 200] loss: 0.328
[Epoch 4, Batch 300] loss: 0.344
[Epoch 4, 

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms

# 1. Завантаження даних
transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,), (0.5,))])

trainset = torchvision.datasets.FashionMNIST(root='./data', train=True, download=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)

testset = torchvision.datasets.FashionMNIST(root='./data', train=False, download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=64, shuffle=False)

# 2. Визначення простої нейронної мережі
class SimpleNet(nn.Module):
    def __init__(self):
        super(SimpleNet, self).__init__()
        self.fc1 = nn.Linear(28 * 28, 128)  # Прихований шар
        self.fc2 = nn.Linear(128, 10)       # Вихідний шар

    def forward(self, x):
        x = x.view(-1, 28 * 28)  # Перетворення зображення у вектор
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

net = SimpleNet()

# 3. Визначення функції втрат та оптимізатора
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr=0.01, momentum=0.9)

# 4. Тренування нейронної мережі
for epoch in range(5):  # Кількість епох
    for i, data in enumerate(trainloader, 0):
        inputs, labels = data

        optimizer.zero_grad()  # Очищення градієнтів

        outputs = net(inputs)  # Передбачення мережі
        loss = criterion(outputs, labels)  # Обчислення втрат
        loss.backward()  # Зворотне поширення
        optimizer.step()  # Оновлення ваг

print('Finished Training')

# 5. Оцінка нейронної мережі на тестовому наборі даних
correct = 0
total = 0
with torch.no_grad():  # Відключення градієнтів для економії ресурсів
    for data in testloader:
        images, labels = data
        outputs = net(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

print(f'Accuracy of the network on the 10000 test images: {100 * correct / total:.2f}%')


Finished Training
Accuracy of the network on the 10000 test images: 86.79%


In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
from PIL import Image
import matplotlib.pyplot as plt

# 1. Завантаження даних
transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

trainset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)

testset = torchvision.datasets.CIFAR10(root='./data', train=False, download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=64, shuffle=False)

# 2. Визначення простої нейронної мережі
class SimpleNet(nn.Module):
    def __init__(self):
        super(SimpleNet, self).__init__()
        self.fc1 = nn.Linear(32 * 32 * 3, 512)
        self.fc2 = nn.Linear(512, 256)
        self.fc3 = nn.Linear(256, 10)

    def forward(self, x):
        x = x.view(-1, 32 * 32 * 3)  # Перетворення зображення у вектор
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        x = self.fc3(x)
        return x

net = SimpleNet()

# 3. Визначення функції втрат та оптимізатора
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr=0.01, momentum=0.9)

# 4. Тренування нейронної мережі
for epoch in range(5):  # Кількість епох
    for i, data in enumerate(trainloader, 0):
        inputs, labels = data

        optimizer.zero_grad()  # Очищення градієнтів

        outputs = net(inputs)  # Передбачення мережі
        loss = criterion(outputs, labels)  # Обчислення втрат
        loss.backward()  # Зворотне поширення
        optimizer.step()  # Оновлення ваг

print('Finished Training')

# 5. Оцінка нейронної мережі на тестовому наборі даних
correct = 0
total = 0
with torch.no_grad():  # Відключення градієнтів для економії ресурсів
    for data in testloader:
        images, labels = data
        outputs = net(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

print(f'Accuracy of the network on the 10000 test images: {100 * correct / total:.2f}%')

# 6. Оцінка нових даних

# Приклад нового зображення (використовуйте своє власне зображення)
image_path = 'C:\\Users\\Penis345\\OneDrive\\Desktop\\-Главная-85-2.webp'  # Замість 'path_to_new_cifar_image.png' вкажіть шлях до вашого зображення

# Завантаження та перетворення зображення
image = Image.open(image_path).convert('RGB')  # Конвертуємо в RGB
image = image.resize((32, 32))  # Зміна розміру до 32x32 пікселів
image = transform(image)
image = image.unsqueeze(0)  # Додаємо batch dimension

# Оцінка нових даних
with torch.no_grad():
    outputs = net(image)
    _, predicted = torch.max(outputs.data, 1)

# Виведення передбаченого класу
classes = ('plane', 'car', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck')
print(f'Predicted class: {classes[predicted.item()]}')

# Якщо ви хочете побачити зображення
plt.imshow(Image.open(image_path))
plt.title(f'Predicted class: {classes[predicted.item()]}')
plt.show()


Files already downloaded and verified
Files already downloaded and verified
Finished Training
Accuracy of the network on the 10000 test images: 53.99%


FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Penis345\\OneDrive\\Desktop\\-Главная-85-2.webp'

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
from torchvision.utils import make_grid

import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
transform = transforms.ToTensor()

In [6]:
train_data = datasets.MNIST(root='/cnn_data',train=True, download=True, transform=transform)

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 9912422/9912422 [00:00<00:00, 50485430.51it/s]


Extracting /cnn_data/MNIST/raw/train-images-idx3-ubyte.gz to /cnn_data/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 28881/28881 [00:00<00:00, 1656239.40it/s]


Extracting /cnn_data/MNIST/raw/train-labels-idx1-ubyte.gz to /cnn_data/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 1648877/1648877 [00:00<00:00, 13269399.12it/s]


Extracting /cnn_data/MNIST/raw/t10k-images-idx3-ubyte.gz to /cnn_data/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 4542/4542 [00:00<00:00, 7307452.54it/s]

Extracting /cnn_data/MNIST/raw/t10k-labels-idx1-ubyte.gz to /cnn_data/MNIST/raw



In [7]:
test_data = datasets.MNIST(root='/cnn_data',train=False, download=True, transform=transform)

In [8]:
train_data

Dataset MNIST
    Number of datapoints: 60000
    Root location: /cnn_data
    Split: Train
    StandardTransform
Transform: ToTensor()

In [9]:
test_data

Dataset MNIST
    Number of datapoints: 10000
    Root location: /cnn_data
    Split: Test
    StandardTransform
Transform: ToTensor()

In [10]:
pwd

'/content'

In [11]:
ls

sample_data/


In [12]:
cd ../

/


In [13]:
pwd

'/'

In [14]:
ls

bin@       cuda-keyring_1.0-1_all.deb  home/    lib64@   NGC-DL-CONTAINER-LICENSE  run/   tmp/
boot/      datalab/                    kaggle/  libx32@  opt/                      sbin@  tools/
cnn_data/  dev/                        lib@     media/   proc/                     srv/   usr/
content/   etc/                        lib32@   mnt/     root/                     sys/   var/


In [15]:
cd cnn_data

/cnn_data


In [16]:
ls

MNIST/


In [17]:
train_loader = DataLoader(train_data, batch_size = 10, shuffle=True)
test_loader = DataLoader(test_data, batch_size = 10, shuffle=False)

In [19]:
conv1 = nn.Conv2d(1, 6, 3, 1)
conv2 = nn.Conv2d(6, 16, 3, 1)

In [20]:
for i, (X_Train, y_train) in enumerate(train_data):
  break

In [21]:
X_Train

tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,

In [22]:
X_Train.shape

torch.Size([1, 28, 28])

In [24]:
x = X_Train.view(1, 1, 28, 28)

In [25]:
x = F.relu(conv1(x))

In [26]:
x

tensor([[[[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          ...,
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],

         [[0.2367, 0.2367, 0.2367,  ..., 0.2367, 0.2367, 0.2367],
          [0.2367, 0.2367, 0.2367,  ..., 0.2367, 0.2367, 0.2367],
          [0.2367, 0.2367, 0.2367,  ..., 0.2367, 0.2367, 0.2367],
          ...,
          [0.2367, 0.2367, 0.2529,  ..., 0.2367, 0.2367, 0.2367],
          [0.2367, 0.2367, 0.2911,  ..., 0.2367, 0.2367, 0.2367],
          [0.2367, 0.2367, 0.2367,  ..., 0.2367, 0.2367, 0.2367]],

         [[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0

In [27]:
x.shape

torch.Size([1, 6, 26, 26])

In [29]:
x = F.max_pool2d(x, 2, 2)

In [30]:
x.shape

torch.Size([1, 6, 13, 13])

In [31]:
x = F.relu(conv2(x))

In [32]:
x.shape

torch.Size([1, 16, 11, 11])

In [33]:
x = F.max_pool2d(x, 2, 2)

In [34]:
x.shape

torch.Size([1, 16, 5, 5])

In [35]:
x = F.max_pool2d(x,2,2)

In [36]:
x.shape

torch.Size([1, 16, 2, 2])

In [38]:
transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.1307,), (0.3081,))])

trainset = datasets.MNIST(root='./data', train=True, download=True, transform=transform)
testset = datasets.MNIST(root='./data', train=False, download=True, transform=transform)

trainloader = DataLoader(trainset, batch_size=64, shuffle=True)
testloader = DataLoader(testset, batch_size=1000, shuffle=False)


class SimpleCNN(nn.Module):
  def __init__(self):
    super(SimpleCNN, self).__init__()
    self.conv1 = nn.Conv2d(1, 32, kernel_size=3, stride=1, padding=1)
    self.conv2 = nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1)
    self.pool = nn.MaxPool2d(kernel_size=2, stride=1, padding=1)

    self.fc1 = nn.Linear(64 * 7 * 7, 128)
    self.fc2 = nn.Linear(128, 10)

    def forward(self, x):
      x = F.relu(conv1(x))
      x = self.pool(x)
      x = F.relu(conv2(x))
      x = self.pool(x)

      x = x.view(-1, 64 * 7 * 7)
      x = F.relu(self.fc1(x))
      x = self.fc2(x)
      return x

net = SimpeCNN()
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(net.parameters(), ls=0.001)

num_epochs = 5

for epoch in range(num_epochs):
  net.train()
  running_loss = 0.0
  for inputs, label in trainloader:
    optimizer.zero_glad()
    outputs = net(inputs)
    loss = criterion(outputs, labels)
    loss.backward()
    optimizer.step()
    running_loss += loss.item()
  print(f'Epoch {epoch+1}, Loss: {running_loss/len(trainloader)}')

print('Finished Training')

net.eval()
correct = 0
total = 0

with torch.no_grad():
  for inputs, labels in testloader:
    outputs = net(inputs)
    _, predicted = torch.max(outputs.data, 1)
    total += labels.size(0)
    correct += (predicted == labels).sum().item()

print(f'Accuracy on test set: {100 * correct / total}%')

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 9912422/9912422 [00:00<00:00, 51214292.26it/s]


Extracting ./data/MNIST/raw/train-images-idx3-ubyte.gz to ./data/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 28881/28881 [00:00<00:00, 2477161.89it/s]


Extracting ./data/MNIST/raw/train-labels-idx1-ubyte.gz to ./data/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 1648877/1648877 [00:00<00:00, 13547528.55it/s]


Extracting ./data/MNIST/raw/t10k-images-idx3-ubyte.gz to ./data/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 4542/4542 [00:00<00:00, 3944208.85it/s]

Extracting ./data/MNIST/raw/t10k-labels-idx1-ubyte.gz to ./data/MNIST/raw



NameError: name 'SimpeCNN' is not defined