<a href="https://colab.research.google.com/github/OleksandrKarpenkoUA/pytorch-tutorial-for-me/blob/main/Pytorch_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn
import torchvision as tv

import numpy as np
import matplotlib.pyplot as plt
import cv2
import os

In [ ]:
trans = tv.transforms.Compose[{
    tv.transforms.ToTensor()
}]

In [ ]:
ds_mnist = tv.datasets.MNISt('./datasets', download=True. transform=trans)

Package                          Version
-------------------------------- ---------------------
absl-py                          1.4.0
aiohttp                          3.9.5
aiosignal                        1.3.1
alabaster                        0.7.16
albumentations                   1.3.1
altair                           4.2.2
annotated-types                  0.7.0
anyio                            3.7.1
argon2-cffi                      23.1.0
argon2-cffi-bindings             21.2.0
array_record                     0.5.1
arviz                            0.15.1
astropy                          5.3.4
astunparse                       1.6.3
async-timeout                    4.0.3
atpublic                         4.1.0
attrs                            23.2.0
audioread                        3.0.1
autograd                         1.6.2
Babel                            2.15.0
backcall                         0.2.0
beautifulsoup4                   4.12.3
bidict                           0.23.1

In [5]:
data = [1, 2, 3]
tensor = torch.tensor(data)
tensor

tensor([1, 2, 3])

In [6]:
tensor = torch.ones(2, 3)
tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
import numpy as np
np_array = np.array([[1, 2, 3], [4, 5, 6]])
np_array

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
tensor = torch.from_numpy(np_array)
tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
tensor = torch.tensor([1, 2, 3])

In [11]:
tensor

tensor([1, 2, 3])

In [12]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
rand_tensor = torch.rand(2, 3, 4)
rand_tensor

tensor([[[0.0407, 0.6728, 0.2673, 0.7009],
         [0.0466, 0.1553, 0.3590, 0.1868],
         [0.5699, 0.9224, 0.6546, 0.0081]],

        [[0.5450, 0.2244, 0.0330, 0.9774],
         [0.7518, 0.1127, 0.9953, 0.7108],
         [0.0845, 0.6590, 0.5545, 0.1939]]])

In [16]:
rand_tensor = torch.rand(2, 3,)
rand_tensor

tensor([[0.6132, 0.8884, 0.6487],
        [0.2902, 0.6305, 0.5569]])

In [17]:
rand_tensor.device

device(type='cpu')

In [18]:
rand_tensor.shape

torch.Size([2, 3])

In [19]:
rand_tensor.dtype

torch.float32

In [23]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor = tensor.reshape(6)
tensor

tensor([1, 2, 3, 4, 5, 6])

In [24]:
tensor[:3]

tensor([1, 2, 3])

In [32]:
tensor[2:5]

tensor([3, 4, 5])

In [33]:
tensor[1, -1]

IndexError: too many indices for tensor of dimension 1

In [45]:
tensor = torch.tensor([[1, 2, 3, 102, 12, 111], [4, 5, 6, 7, 8, 9]])
tensor.view(2, -1)

tensor([[  1,   2,   3, 102,  12, 111],
        [  4,   5,   6,   7,   8,   9]])

In [48]:
tensor.reshape(-1, 3)

tensor([[  1,   2,   3],
        [102,  12, 111],
        [  4,   5,   6],
        [  7,   8,   9]])

In [56]:
data_a = np.arange(0, 5)
data_b = np.arange(5, 10)

In [57]:
data_a

array([0, 1, 2, 3, 4])

In [58]:
data_b

array([5, 6, 7, 8, 9])

In [67]:
tensor_a = torch.tensor([1, 2, 3])
tensor_b = torch.tensor([4, 5, 6])


In [68]:
# add
torch.add(tensor_a, tensor_b)

tensor([5, 7, 9])

In [69]:
tensor_a

tensor([1, 2, 3])

In [88]:
add = tensor_a.add_(tensor_b) # tensor_a = tensor_a + tensor_b

In [89]:
add

tensor([ 9, 12, 15])

In [90]:
# sub
torch.sub(tensor_b, tensor_a)

tensor([-5, -7, -9])

In [91]:
# mul
torch.mul(tensor_a, tensor_b)

tensor([36, 60, 90])

In [92]:
# div
torch.div(tensor_b, tensor_a)

tensor([0.4444, 0.4167, 0.4000])

In [93]:
tensor_a % tensor_b

tensor([1, 2, 3])

In [94]:
torch.pow(tensor_a, tensor_b)

tensor([    6561,   248832, 11390625])

In [96]:
# remainder
torch.remainder(tensor_b, tensor_a)

tensor([4, 5, 6])